package danger.orespawn.integrations.compat.jei;

import java.util.List;
import java.util.Optional;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import danger.orespawn.integrations.OreSpawnIntegrations;
import mezz.jei.api.IModPlugin;
import mezz.jei.api.JeiPlugin;
import mezz.jei.api.constants.RecipeTypes;
import mezz.jei.api.registration.IIngredientAliasRegistration;
import mezz.jei.api.registration.IModInfoRegistration;
import mezz.jei.api.registration.IRecipeCatalystRegistration;
import mezz.jei.api.registration.IRecipeRegistration;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;

/**
 * JEI plugin for OreSpawn. Discovered by JEI's own annotation scan
 * ({@code mezz.jei.neoforge.startup.ForgePluginFinder}), so this class is
 * never touched when JEI is absent and needs no wiring from the main mod
 * class.
 *
 * <p>Everything registered here was verified against the shipped jars:
 * <ul>
 *   <li>Ant travel targets come from the bytecode of
 *       {@code danger.orespawn.entity.EntityAnt#getTargetDimension} and its
 *       subclasses (black ant &rarr; Utopia, red ant &rarr; Mining,
 *       unstable ant &rarr; Islands, termite &rarr; Crystal, rainbow ant
 *       &rarr; Village; both termite blocks spawn the same Crystal-bound
 *       termite; right-clicking the ant in its home dimension returns you
 *       to the Overworld).</li>
 *   <li>Boss-egg chain from OreSpawn's own recipe JSONs: nine
 *       {@code *_part_spawn_block} (world-generated by
 *       {@code SpawnOresPoolFeature}) craft into the full spawn block,
 *       which combines with a water bucket into the live spawn egg.</li>
 *   <li>Ray Gun repair ({@code ray_gun_repair.json}: ray gun + redstone
 *       block), nugget economy ({@code *_nugget_smelting.json} /
 *       {@code *_ingot_from_nuggets.json}) and boss loot tables
 *       (royal gear from The King, Royal Guardian Sword from King and
 *       Queen) all read straight from the orespawn jar.</li>
 *   <li>The Crystal Workbench menu crafts vanilla
 *       {@code RecipeType.CRAFTING} recipes and the Crystal Furnace smelts
 *       vanilla {@code RecipeType.SMELTING} recipes with normal fuel, so
 *       both are registered as catalysts for those categories.</li>
 * </ul>
 */
@JeiPlugin
public class OreSpawnJeiPlugin implements IModPlugin {

    private static final Logger LOGGER = LoggerFactory.getLogger("OreSpawnIntegrations/JEI");
    private static final String ORESPAWN = "orespawn";
    private static final ResourceLocation UID =
            ResourceLocation.fromNamespaceAndPath(OreSpawnIntegrations.MODID, "jei");
    private static final String INFO_KEY_PREFIX = "jei." + OreSpawnIntegrations.MODID + ".info.";

    /** Items whose info page key is derived from their own registry path. */
    private static final String[] SINGLE_INFO_PAGES = {
            // Dimension ant blocks - the six travel hubs.
            "ant_block",
            "red_ant_block",
            "unstable_ant_block",
            "termite_block",
            "crystal_termite_block",
            "rainbow_ant_block",
            // Ultraboss ancient-egg chain.
            "godzilla_spawn_block",
            "the_king_spawn_block",
            "the_queen_spawn_block",
            "godzilla_part_spawn_block",
            "the_king_part_spawn_block",
            "the_queen_part_spawn_block",
            // Uncraftables and odd economies.
            "ray_gun",
            "royal_guardian_sword",
            "uranium_nugget",
            "titanium_nugget",
            "kraken_repellent",
            "cage_empty",
            "zoo_keeper",
    };

    private static final String[] ROYAL_ARMOR = {
            "royal_helmet", "royal_chestplate", "royal_leggings", "royal_boots",
    };

    private static final String[] ZOO_CAGES = {
            "zoo_cage_2", "zoo_cage_4", "zoo_cage_6", "zoo_cage_8", "zoo_cage_10",
    };

    /** First element is the orespawn item path, the rest are search aliases. */
    private static final String[][] ALIASES = {
            {"ant_block", "dimension ant", "ant portal", "utopia"},
            {"red_ant_block", "dimension ant", "ant portal", "mining dimension"},
            {"unstable_ant_block", "dimension ant", "ant portal", "island dimension"},
            {"termite_block", "dimension ant", "ant portal", "crystal dimension"},
            {"crystal_termite_block", "dimension ant", "ant portal", "crystal dimension"},
            {"rainbow_ant_block", "dimension ant", "ant portal", "village dimension"},
            // Display names say "Mobzilla" while registry ids say godzilla -
            // bridge both search terms.
            {"godzilla_spawn_block", "godzilla", "ancient egg", "boss summon"},
            {"godzilla_part_spawn_block", "godzilla", "ancient egg part"},
            {"godzilla_scale", "mobzilla scale", "boss drop"},
            {"the_king_spawn_block", "ancient egg", "boss summon"},
            {"the_king_part_spawn_block", "ancient egg part"},
            {"the_queen_spawn_block", "ancient egg", "boss summon"},
            {"the_queen_part_spawn_block", "ancient egg part"},
            {"queen_scale", "boss drop"},
            {"ray_gun", "laser", "blaster"},
            {"royal_helmet", "boss drop", "king drop"},
            {"royal_chestplate", "boss drop", "king drop"},
            {"royal_leggings", "boss drop", "king drop"},
            {"royal_boots", "boss drop", "king drop"},
            {"royal_guardian_sword", "boss drop", "king drop", "rgs"},
            {"kraken_repellent", "anti kraken", "buoy"},
            {"zoo_cage_2", "zoo", "pen", "enclosure"},
            {"zoo_cage_4", "zoo", "pen", "enclosure"},
            {"zoo_cage_6", "zoo", "pen", "enclosure"},
            {"zoo_cage_8", "zoo", "pen", "enclosure"},
            {"zoo_cage_10", "zoo", "pen", "enclosure"},
            {"cage_empty", "mob catcher", "capture"},
            {"zoo_keeper", "no despawn", "persistent"},
    };

    @Override
    public ResourceLocation getPluginUid() {
        return UID;
    }

    @Override
    public void registerRecipes(IRecipeRegistration registration) {
        try {
            for (String path : SINGLE_INFO_PAGES) {
                item(path).ifPresent(it ->
                        registration.addIngredientInfo(it, Component.translatable(INFO_KEY_PREFIX + path)));
            }
            addGroupInfo(registration, ROYAL_ARMOR, "royal_armor");
            addGroupInfo(registration, ZOO_CAGES, "zoo_cage");
        } catch (Exception | LinkageError e) {
            LOGGER.error("Failed to register OreSpawn JEI info pages - continuing without them", e);
        }
    }

    @Override
    public void registerRecipeCatalysts(IRecipeCatalystRegistration registration) {
        try {
            item("crystal_workbench").ifPresent(it ->
                    registration.addRecipeCatalyst(it, RecipeTypes.CRAFTING));
            item("crystal_furnace").ifPresent(it ->
                    registration.addRecipeCatalyst(it, RecipeTypes.SMELTING, RecipeTypes.FUELING));
        } catch (Exception | LinkageError e) {
            LOGGER.error("Failed to register OreSpawn JEI catalysts - continuing without them", e);
        }
    }

    @Override
    public void registerIngredientAliases(IIngredientAliasRegistration registration) {
        try {
            for (String[] entry : ALIASES) {
                item(entry[0]).ifPresent(it ->
                        registration.addAliases(it, List.of(entry).subList(1, entry.length)));
            }
        } catch (Exception | LinkageError e) {
            LOGGER.error("Failed to register OreSpawn JEI search aliases - continuing without them", e);
        }
    }

    @Override
    public void registerModInfo(IModInfoRegistration registration) {
        try {
            registration.addModAliases(ORESPAWN, "ore spawn", "crazy craft", "crazycraft");
        } catch (Exception | LinkageError e) {
            LOGGER.error("Failed to register OreSpawn JEI mod aliases - continuing without them", e);
        }
    }

    /** One shared info page shown on every item of the group. */
    private static void addGroupInfo(IRecipeRegistration registration, String[] paths, String keySuffix) {
        List<ItemStack> stacks = java.util.Arrays.stream(paths)
                .map(OreSpawnJeiPlugin::item)
                .flatMap(Optional::stream)
                .map(ItemStack::new)
                .toList();
        if (!stacks.isEmpty()) {
            registration.addItemStackInfo(stacks, Component.translatable(INFO_KEY_PREFIX + keySuffix));
        }
    }

    /**
     * Registry-safe lookup: the ITEM registry is defaulted (missing ids
     * resolve to air), so getOptional + a warn keeps a renamed id in a
     * future OreSpawn beta from silently attaching pages to air.
     */
    private static Optional<Item> item(String path) {
        ResourceLocation id = ResourceLocation.fromNamespaceAndPath(ORESPAWN, path);
        Optional<Item> found = BuiltInRegistries.ITEM.getOptional(id);
        if (found.isEmpty()) {
            LOGGER.warn("OreSpawn item {} not found - JEI entry skipped", id);
        }
        return found;
    }
}
